name: Hello world workflow

on:
  issues:
    types: [opened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello world
        run: echo "hello world from workflow"
        shell: bash
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            Fear not for your issues has been seen and will be sorted out soon
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
    
    
  
  
